//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÜrünFiltreleme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Özellikler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Özellikler()
        {
            this.ÜrünOzelllik = new HashSet<ÜrünOzelllik>();
        }
    
        public int Id { get; set; }
        public string Doku { get; set; }
        public string KullanımAlanı { get; set; }
        public string Malzeme { get; set; }
        public string Boyut { get; set; }
        public string Renk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÜrünOzelllik> ÜrünOzelllik { get; set; }
    }
}
