//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÜrünFiltreleme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ÜrünOzelllik
    {
        public int Id { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> OzellikId { get; set; }
    
        public virtual Özellikler Özellikler { get; set; }
        public virtual Ürünler Ürünler { get; set; }
    }
}
